name: Music Store Docker Deploy

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          cd src
          docker build . --tag music-store:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/music-store:${{ github.sha }}
      
      - name: Login to Azure
        uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-container-deploy@v1
        with:
          app-name: 'music-store-docker'
          images: '${{ secrets.DOCKER_USERNAME }}/music-store:${{ github.sha }}'
      
