name: Music Store Build

on:
  push:
    branches: 
      - release/*
  pull_request:
    branches:
      - master
      - release/*  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup .NET Core 3.1.102
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build with dotnet
      run: dotnet build src/MusicStore/MusicStore.Web/*.csproj --configuration Release
    - name: Run Unit Tests
      run: dotnet test src\MusicStore\UnitTests\**\*.Tests.csproj
